### ISSUE TITLE
Applicability for multi-tenant (multi realm) application

### ISSUE THREAD

**Issue by snehil2112** [5-stones/nest-oidc#3]
I have developed a multi tenant application where I am using realm per tenant.
As per the documentation, issuer uri containing realm name has to be provided in the global configuration but in case of multi tenant application, realm is identified from the request object.
Is there a method which we can use to extract the realm name from the request object.

**Comment by jspizziri** [comment]
Sorry, just saw this. Not currently, you're probably best served by forking this project and making some modifications to it.
